### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Speedy1991** [ddanier/fabdeploit#5]
I just tried around with your fabdeploit and got this error:

```
fab -u git -H localhost deploy
[localhost] Executing task 'deploy'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/speedy/git/django_deploy/fabfile.py", line 43, in deploy
    commit = git.release()
  File "/usr/local/lib/python2.7/dist-packages/fabdeploit/git.py", line 292, in release
    self.create_release_commit(message=message)
  File "/usr/local/lib/python2.7/dist-packages/fabdeploit/git.py", line 226, in create_release_commit
    commit = repo.heads[self.release_branch].commit
  File "/usr/local/lib/python2.7/dist-packages/git/util.py", line 893, in __getitem__
    raise IndexError("No item found with id %r" % (self._prefix + index))
IndexError: No item found with id 'master'

```

__Steps to reproduce:__
- use the django example from docs
- setup a simple django app
- `git init`
- `git checkout -b master`
- `fab -u <user> -H <host> deploy`

__Solution:__
The master/production branch must be commited (inital commit is enough) before running fab. This is not really an error in my eyes, but some documentation would be nice

**Comment by ddanier** [comment]
Good catch!

Feel free to open a pull request ;-)

**Comment by Speedy1991** [comment]
I'll submit a PR the next days
